import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useMemo, useState, type FormEvent } from "react";
import { AlertTriangle, ArrowDownLeft, Box, Check, ChevronLeft, Heart, Move3D, Search, Sparkles, Wrench } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";

type MediaItem={type?:string;url?:string;alt?:string};
type Product={product_id:string;public_slug:string;model_code:string;name_ar:string;description:string|null;category_slug:string|null;category_name_ar:string|null;price_with_vat:number;production_history_count:number;selling_mode:string;media:MediaItem[]|null};
const categories=[["majlis-sofas","المجالس والكنب"],["bedrooms","غرف النوم"],["offices","المكاتب"],["tables","الطاولات"],["chairs","الكراسي"],["storage","الخزائن والتخزين"],["custom","نماذج حسب الطلب"]];
const sar=new Intl.NumberFormat("ar-SA",{style:"currency",currency:"SAR",maximumFractionDigits:2});
const SEARCH_EDGE="https://vmswbmkkgvnjhznxbsdz.supabase.co/functions/v1/storefront-search";
export const Route=createFileRoute("/store/")({component:StoreHome});
function imageOf(product?:Product){return product?.media?.find(m=>m.type!=="glb"&&m.type!=="usdz")?.url}
function isReference(product:Product){return product.selling_mode==="reference"||Number(product.price_with_vat)<=0}

function StoreHome(){
 const [products,setProducts]=useState<Product[]>([]),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState<string|null>(null),[q,setQ]=useState(""),[category,setCategory]=useState(""),[intent,setIntent]=useState<string|null>(null),[favorites,setFavorites]=useState<string[]>([]);
 useEffect(()=>{const p=new URLSearchParams(location.search);setQ(p.get("q")??"");setCategory(p.get("category")??"")},[]);
 useEffect(()=>{let alive=true;setLoading(true);setLoadError(null);setIntent(null);(async()=>{try{if(q.trim()){const r=await fetch(SEARCH_EDGE,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({q:q.trim()})});let b:Record<string,unknown>={};try{b=await r.json()}catch{b={}}if(!r.ok){console.error("storefront search failed",{status:r.status,query:q,error:b.error});throw new Error("SEARCH_EDGE_FAILED")}if(alive){setProducts(Array.isArray(b.products)?b.products as Product[]:[]);setIntent(typeof b.intent_ar==="string"?b.intent_ar:null)}}else{let query=(supabase as any).from("store_public_catalog").select("*").order("published_at",{ascending:false}).limit(500);if(category)query=query.eq("category_slug",category);const{data,error:queryError}=await query;if(queryError){console.error("store catalog query failed",{category,code:queryError.code,message:queryError.message});throw new Error("CATALOG_QUERY_FAILED")}if(alive)setProducts((data??[]) as Product[])}}catch(err){if(!alive)return;console.error("store catalog load exception",{query:q,category,error:err instanceof Error?err.message:"unknown"});setProducts([]);setLoadError("حدث عطل تقني أثناء تحميل الموديلات. يرجى إعادة المحاولة.")}finally{if(alive)setLoading(false)}})();return()=>{alive=false}},[q,category]);
 const mostProduced=useMemo(()=>products.filter(p=>Number(p.production_history_count)>0).sort((a,b)=>Number(b.production_history_count)-Number(a.production_history_count)).slice(0,4),[products]);
 const scenes=useMemo(()=>products.filter(p=>Boolean(imageOf(p))).slice(0,4),[products]);
 const referenceCount=useMemo(()=>products.filter(isReference).length,[products]);
 function search(e:FormEvent<HTMLFormElement>){e.preventDefault();const value=String(new FormData(e.currentTarget).get("q")??"").trim();setCategory("");setQ(value);history.replaceState(null,"",value?`/store?q=${encodeURIComponent(value)}`:"/store")}
 function chooseCategory(slug:string){setQ("");setCategory(slug);history.replaceState(null,"",`/store?category=${slug}`)}
 function toggleFavorite(id:string){setFavorites(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id])}
 return <main className="relative overflow-hidden bg-[#071a2b] text-white">
  <div className="pointer-events-none fixed inset-0 -z-0"><div className="absolute -right-40 -top-40 h-[520px] w-[520px] rounded-full bg-[#7c8a96]/10 blur-3xl"/><div className="absolute -left-40 top-[42%] h-[460px] w-[460px] rounded-full bg-slate-500/5 blur-3xl"/></div>
  <section aria-label="معرض المقرن التفاعلي" className="relative z-10 h-[100svh] min-h-[640px] snap-y snap-mandatory overflow-y-auto overscroll-contain scroll-smooth [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">
   {(scenes.length?scenes:[undefined,undefined,undefined,undefined]).map((p,i)=>{const bg=imageOf(p);const labels=["المعيشة والمجالس","مجموعات مختارة","نماذج الكتالوج","التفصيل الخاص"];const fallback=["أثاث يليق بمساحتك","اختر النموذج الأقرب لفكرتك","كل الموديلات في مكان واحد","فكرتك تبدأ من هنا"];return <article key={p?.product_id??`scene-${i}`} className="relative isolate flex min-h-[100svh] snap-start items-end overflow-hidden border-b border-white/10 px-6 pb-16 pt-28 sm:items-center sm:pb-0 lg:px-10">
    {bg?<img src={bg} alt={p?.name_ar??""} className="absolute inset-0 -z-30 h-full w-full object-cover transition duration-[1400ms] ease-out hover:scale-[1.025]"/>:<div className="absolute inset-0 -z-30 bg-[radial-gradient(circle_at_20%_20%,rgba(197,203,209,.18),transparent_35%),linear-gradient(135deg,#0b2236,#061521)]"/>}<div className="absolute inset-0 -z-20 bg-[linear-gradient(90deg,rgba(5,15,25,.18)_0%,rgba(5,15,25,.46)_48%,rgba(5,15,25,.94)_100%)]"/><div className="absolute inset-x-0 bottom-0 -z-10 h-1/2 bg-gradient-to-t from-[#061521]/80 to-transparent"/>
    <div className="mx-auto w-full max-w-7xl"><div className="max-w-3xl"><div className="mb-4 inline-flex items-center gap-2 rounded-full border border-white/15 bg-black/25 px-4 py-2 text-xs text-white/75 backdrop-blur"><Sparkles className="h-4 w-4"/>{labels[i]}</div>{i===0?<h1 className="text-5xl font-black leading-[1.04] sm:text-7xl lg:text-8xl">{p?.name_ar??fallback[i]}</h1>:<h2 className="text-5xl font-black leading-[1.04] sm:text-7xl lg:text-8xl">{p?.name_ar??fallback[i]}</h2>}<p className="mt-5 max-w-2xl text-sm leading-8 text-white/65 sm:text-base">{p?.description??"استكشف موديلات مصنع المقرن والمراجع التصميمية، ثم اختر النموذج المناسب ليتم تسعيره حسب المقاس والخامة والمواصفات المعتمدة."}</p><div className="mt-8 flex flex-wrap gap-3">{p?<Link to="/store/$slug" params={{slug:p.public_slug}} className="inline-flex items-center gap-2 rounded-full bg-white px-6 py-3 text-sm font-black text-black">استكشف الموديل <ChevronLeft className="h-4 w-4"/></Link>:<a href="#models" className="inline-flex items-center gap-2 rounded-full bg-white px-6 py-3 text-sm font-black text-black">تصفح الموديلات <ArrowDownLeft className="h-4 w-4"/></a>}<a href="#models" className="rounded-full border border-white/20 bg-black/20 px-6 py-3 text-sm font-bold text-white/75 backdrop-blur">كل الموديلات</a></div></div></div>
    <div className="absolute bottom-7 left-6 flex items-center gap-3 text-[11px] text-white/55 sm:left-10"><span className="text-lg font-black text-white">0{i+1}</span><span className="h-px w-14 bg-white/35"/><span>{p?.category_name_ar??labels[i]}</span></div>{i<3&&<div className="absolute bottom-7 right-6 hidden items-center gap-2 text-[11px] text-white/45 sm:flex sm:right-10"><ArrowDownLeft className="h-4 w-4"/> مرّر للمشهد التالي</div>}
   </article>})}
  </section>
  <section id="search" className="relative z-10 mx-auto max-w-7xl px-6 py-8"><div className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><div className="text-xs font-bold tracking-[.18em] text-[#b9bec6]">ALMUQRIN SHOWROOM</div><h2 className="mt-2 text-3xl font-black sm:text-4xl">اختر الموديل وابدأ التخصيص</h2></div>{referenceCount>0&&<div className="rounded-full border border-white/10 bg-white/[.04] px-4 py-2 text-xs text-white/55">{referenceCount} موديل مرجعي متاح</div>}</div><form onSubmit={search} className="flex flex-col gap-3 rounded-[24px] border border-white/10 bg-white/[0.035] p-3 backdrop-blur md:flex-row"><div className="flex flex-1 items-center gap-3 px-3"><Search className="h-5 w-5 text-[#b9bec6]"/><input name="q" defaultValue={q} className="w-full bg-transparent py-3 text-sm text-white outline-none placeholder:text-white/25" placeholder="ابحث برقم الموديل أو الوصف"/></div><button className="rounded-2xl bg-[#b9bec6] px-7 py-3 text-sm font-black text-black">بحث في الموديلات</button></form>{intent&&<div className="mt-3 rounded-xl border border-white/10 bg-white/[0.03] px-4 py-3 text-xs text-white/50"><b className="text-white/75">فهم البحث:</b> {intent}</div>}<div id="categories" className="mt-4 flex gap-2 overflow-x-auto pb-2">{categories.map(([slug,name])=><button key={slug} type="button" aria-pressed={category===slug} onClick={()=>chooseCategory(slug)} className={`whitespace-nowrap rounded-full border px-4 py-2 text-xs font-bold transition ${category===slug?"border-[#b9bec6] bg-[#b9bec6] text-black":"border-white/10 bg-white/[0.025] text-white/50"}`}>{name}</button>)}</div></section>
  <section id="models" className="relative z-10 mx-auto max-w-7xl px-6 py-14"><div className="flex flex-wrap items-end justify-between gap-4"><div><div className="text-xs font-bold tracking-[.18em] text-[#b9bec6]">ALMUQRIN COLLECTION</div><h2 className="mt-2 text-3xl font-black">جميع الموديلات</h2></div><div className="text-xs text-white/30">الموديلات المرجعية تُسعّر بعد تحديد المقاس والخامة</div></div>{loading?<div className="mt-8 text-sm text-white/40">جارٍ تحميل الموديلات…</div>:loadError?<div className="mt-8 rounded-[30px] border border-amber-300/20 bg-amber-300/5 p-10 text-center"><AlertTriangle className="mx-auto h-10 w-10 text-amber-300"/><h3 className="mt-4 text-xl font-black">تعذر تحميل الموديلات</h3><p className="mt-2 text-sm text-white/50">{loadError}</p><button type="button" onClick={()=>location.reload()} className="mt-5 rounded-full bg-white px-5 py-2.5 text-xs font-black text-black">إعادة المحاولة</button></div>:products.length?<div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{products.map((p,i)=><ProductCard key={p.product_id} product={p} featured={i===0&&!category&&!q} favorite={favorites.includes(p.product_id)} onFavorite={()=>toggleFavorite(p.product_id)}/>)}</div>:<div className="mt-8 rounded-[30px] border border-dashed border-white/15 bg-white/[0.02] p-12 text-center"><Wrench className="mx-auto h-10 w-10 text-[#b9bec6]"/><h3 className="mt-4 text-xl font-black">لا توجد موديلات مطابقة</h3><p className="mt-2 text-sm text-white/35">لا توجد منتجات معتمدة للنشر تطابق البحث حاليًا.</p></div>}</section>
  {mostProduced.length>0&&<section className="relative z-10 mx-auto max-w-7xl px-6 py-10"><div className="rounded-[34px] border border-white/10 bg-[#0b2236] p-8 md:p-12"><div className="text-xs font-bold tracking-[.16em] text-[#b9bec6]">MOST PRODUCED</div><h2 className="mt-2 text-3xl font-black">موديلات مثبتة بسجل إنتاج</h2><div className="mt-8 grid gap-4 md:grid-cols-4">{mostProduced.map((p,i)=><Link key={p.product_id} to="/store/$slug" params={{slug:p.public_slug}} className="rounded-2xl border border-white/10 bg-white/[0.025] p-5"><div className="text-3xl font-black text-[#b9bec6]">0{i+1}</div><div className="mt-4 font-black">{p.name_ar}</div><div className="mt-1 text-xs text-white/35">تم تصنيعه {p.production_history_count} مرة</div></Link>)}</div></div></section>}
  <section id="custom" className="relative z-10 mx-auto max-w-7xl px-6 py-14"><div className="overflow-hidden rounded-[38px] border border-[#b9bec6]/20 bg-[linear-gradient(135deg,#0b2236,#071a2b)] p-8 md:p-14"><div className="grid gap-8 lg:grid-cols-[1fr_.65fr] lg:items-end"><div><div className="flex items-center gap-2 text-xs font-bold text-[#c5cbd1]"><Sparkles className="h-4 w-4"/> أثاث حسب الطلب</div><h2 className="mt-3 text-3xl font-black md:text-5xl">اختر أي موديل وننفذه وفق المواصفات المعتمدة.</h2><p className="mt-5 max-w-2xl leading-8 text-white/45">المراجع المعروضة ليست أسعارًا ثابتة أو ادعاءً بأنها أعمال منفذة؛ يعتمد السعر بعد المقاسات والخامات والمراجعة الفنية.</p></div><a href="#models" className="inline-flex items-center justify-between rounded-2xl bg-white px-5 py-4 text-sm font-black text-black">اختر موديل <ChevronLeft className="h-4 w-4"/></a></div></div></section>
 </main>
}
function ProductCard({product,featured,favorite,onFavorite}:{product:Product;featured:boolean;favorite:boolean;onFavorite:()=>void}){const image=imageOf(product);const has3d=product.media?.some(m=>m.type==="glb");const reference=isReference(product);return <article className={`group relative overflow-hidden rounded-[28px] border border-white/10 bg-[#111419] ${featured?"sm:col-span-2 lg:row-span-2":""}`}><button type="button" onClick={e=>{e.preventDefault();e.stopPropagation();onFavorite()}} className="absolute left-4 top-4 z-20 grid h-10 w-10 place-items-center rounded-full border border-white/15 bg-black/35 text-white backdrop-blur" aria-label="المفضلة"><Heart className={`h-4 w-4 ${favorite?"fill-white":""}`}/></button>{has3d&&<span className="absolute right-4 top-4 z-20 inline-flex items-center gap-1.5 rounded-full border border-white/15 bg-black/35 px-3 py-2 text-[10px] font-bold"><Move3D className="h-3.5 w-3.5"/> 3D READY</span>}<Link to="/store/$slug" params={{slug:product.public_slug}} className="block h-full"><div className={`relative overflow-hidden bg-[#171a1f] ${featured?"min-h-[540px] lg:h-full":"aspect-[4/3]"}`}>{image?<img src={image} loading="lazy" alt={product.name_ar} className="h-full w-full object-cover transition duration-700 group-hover:scale-[1.045]"/>:<div className="flex h-full items-center justify-center"><Box className="h-14 w-14 text-white/15"/></div>}<div className="absolute inset-0 bg-gradient-to-t from-black/95 via-black/15 to-transparent"/><span className="absolute bottom-4 right-4 rounded-full border border-white/10 bg-black/35 px-3 py-1 text-[10px] text-white/55 backdrop-blur">{product.model_code}</span></div><div className={`absolute inset-x-0 bottom-0 p-5 ${featured?"sm:p-7":""}`}><div className="text-[10px] font-semibold tracking-wide text-[#c5cbd1]">{reference?"موديل مرجعي للتنفيذ حسب الطلب":product.category_name_ar??"منتج معتمد"}</div><h3 className={`${featured?"text-2xl sm:text-3xl":"text-xl"} mt-2 font-black`}>{product.name_ar}</h3><p className="mt-2 line-clamp-2 max-w-2xl text-xs leading-6 text-white/45">{product.description}</p><div className="mt-4 flex items-end justify-between gap-4"><div>{reference?<><div className="text-[10px] text-white/30">التسعير</div><div className="mt-1 text-lg font-black">حسب المواصفات</div></>:<><div className="text-[10px] text-white/30">شامل الضريبة</div><div className="mt-1 text-lg font-black">{sar.format(Number(product.price_with_vat))}</div></>}</div><div className="grid h-11 w-11 place-items-center rounded-full bg-white text-black"><ChevronLeft className="h-4 w-4"/></div></div>{featured&&!reference&&<div className="mt-5 hidden gap-3 border-t border-white/10 pt-4 text-[11px] text-white/40 sm:flex"><span className="flex items-center gap-1"><Check className="h-3.5 w-3.5"/> قابل للتخصيص</span><span>صُنّع {product.production_history_count} مرة</span></div>}</div></Link></article>}
