import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { CheckCircle2, Ruler, ShoppingBag, SlidersHorizontal, Sparkles } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { ModelViewer } from "@/components/storefront/model-viewer";

type MediaItem = { type?: string; url?: string; alt?: string };
type Product = { product_id:string; public_slug:string; model_code:string; name_ar:string; name_en:string|null; description:string|null; category_name_ar:string|null; width_mm:number|null; depth_mm:number|null; height_mm:number|null; unit:string; selling_mode:string; colors:string[]; materials:string[]; finish:string|null; specifications:Record<string,unknown>; price_before_vat:number; vat_percent:number; vat_amount:number; price_with_vat:number; production_history_count:number; media:MediaItem[]|null };
const sar = new Intl.NumberFormat("ar-SA", { style:"currency", currency:"SAR", maximumFractionDigits:2 });
const EDGE_URL = "https://vmswbmkkgvnjhznxbsdz.supabase.co/functions/v1/storefront-customization";

export const Route = createFileRoute("/store/$slug")({ component: ProductPage });

function ProductPage(){
  const { slug }=Route.useParams(); const [product,setProduct]=useState<Product|null>(null); const [loading,setLoading]=useState(true); const [added,setAdded]=useState(false); const [sending,setSending]=useState(false); const [sent,setSent]=useState<string|null>(null); const [error,setError]=useState<string|null>(null);
  useEffect(()=>{let alive=true;(async()=>{const {data}=await (supabase as any).from("store_public_catalog").select("*").eq("public_slug",slug).maybeSingle();if(alive){setProduct(data as Product|null);setLoading(false)}})();return()=>{alive=false}},[slug]);
  if(loading)return <main className="mx-auto max-w-7xl px-6 py-16 text-sm text-slate-500">جارٍ تحميل الموديل…</main>;
  if(!product)return <main className="mx-auto max-w-3xl px-6 py-20 text-center"><h1 className="text-3xl font-black">الموديل غير متاح</h1><p className="mt-3 text-slate-500">قد يكون قيد المراجعة أو تم إيقاف نشره.</p></main>;
  const images=(product.media??[]).filter(m=>["factory_photo","design_render","design_image"].includes(m.type??"")&&m.url); const glb=(product.media??[]).find(m=>m.type==="glb")?.url; const canBuy=["standard","both"].includes(product.selling_mode); const canCustomize=["customizable","both"].includes(product.selling_mode);
  function addCart(){const key="almuqrin_store_cart";const list=JSON.parse(localStorage.getItem(key)??"[]") as any[];const item=list.find(x=>x.productId===product.product_id);if(item)item.quantity+=1;else list.push({productId:product.product_id,slug:product.public_slug,name:product.name_ar,price:Number(product.price_with_vat),quantity:1});localStorage.setItem(key,JSON.stringify(list));setAdded(true)}
  async function submitCustomization(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setSending(true);setError(null);setSent(null);const form=new FormData(e.currentTarget);form.set("product_id",product.product_id);form.set("slug",product.public_slug);try{const res=await fetch(EDGE_URL,{method:"POST",body:form});const body=await res.json();if(!res.ok)throw new Error(body.error??"تعذر إرسال الطلب");setSent(body.requestNumber??"تم الإرسال");e.currentTarget.reset()}catch(err){setError(err instanceof Error?err.message:"تعذر إرسال الطلب")}finally{setSending(false)}}
  return <main className="mx-auto max-w-7xl px-6 py-10">
    {sent&&<div className="mb-6 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-bold text-emerald-800">تم إرسال الطلب رقم {sent} إلى منصة المقرن. السعر النهائي بانتظار مراجعة واعتماد المصنع.</div>}
    <div className="grid gap-10 lg:grid-cols-[1.15fr_.85fr]"><section><div className="grid gap-4 sm:grid-cols-2">{images.length?images.map((m,i)=><div key={`${m.url}-${i}`} className={`${i===0?"sm:col-span-2":""} overflow-hidden rounded-[30px] bg-[#e9e4da]`}><img src={m.url!} alt={m.alt??product.name_ar} className="aspect-[4/3] h-full w-full object-cover"/></div>):<div className="sm:col-span-2 flex aspect-[4/3] items-center justify-center rounded-[30px] bg-[#e9e4da] text-sm text-slate-500">ستظهر صور المصنع المعتمدة هنا</div>}</div>{glb&&<div className="mt-5"><ModelViewer src={glb} alt={product.name_ar}/></div>}</section>
      <aside className="lg:sticky lg:top-32 lg:self-start"><div className="text-sm font-bold text-[#8d7657]">{product.category_name_ar??"من إنتاج مصنعنا"}</div><div className="mt-2 text-xs font-semibold text-slate-500">موديل {product.model_code}</div><h1 className="mt-3 text-4xl font-black leading-tight">{product.name_ar}</h1><p className="mt-5 leading-8 text-slate-500">{product.description}</p><div className="mt-7 rounded-[26px] border border-black/10 bg-white p-6"><div className="text-xs text-slate-500">السعر المعتمد شامل ضريبة القيمة المضافة</div><div className="mt-1 text-3xl font-black">{sar.format(Number(product.price_with_vat))}</div><div className="mt-2 text-xs text-slate-500">قبل الضريبة {sar.format(Number(product.price_before_vat))} • VAT {product.vat_percent}%</div></div><div className="mt-5 flex flex-wrap gap-3">{canBuy&&<button onClick={addCart} className="inline-flex items-center gap-2 rounded-full bg-[#17212a] px-6 py-3 text-sm font-black text-white"><ShoppingBag className="h-4 w-4"/>{added?"أضيف إلى السلة":"أضف للسلة"}</button>}{canCustomize&&<a href="#customize" className="inline-flex items-center gap-2 rounded-full border border-black/15 bg-white px-6 py-3 text-sm font-black"><SlidersHorizontal className="h-4 w-4"/>خصص هذا الموديل</a>}</div><p className="mt-5 text-xs leading-6 text-slate-500">السعر للمواصفات والمقاسات الموضحة، وأي تعديل في المقاسات أو الخامات أو الإكسسوارات يتم تسعيره قبل الاعتماد.</p>
      <div className="mt-8 border-t border-black/10 pt-7"><h2 className="font-black">المواصفات</h2><div className="mt-4 grid grid-cols-2 gap-3 text-sm"><Spec label="العرض" value={product.width_mm?`${product.width_mm} مم`:"حسب الموديل"}/><Spec label="العمق" value={product.depth_mm?`${product.depth_mm} مم`:"حسب الموديل"}/><Spec label="الارتفاع" value={product.height_mm?`${product.height_mm} مم`:"حسب الموديل"}/><div className="rounded-2xl bg-white p-4"><CheckCircle2 className="mb-2 h-4 w-4"/><div className="text-xs text-slate-500">سجل الإنتاج</div><b>{product.production_history_count} مرة</b></div></div>{product.materials?.length>0&&<Chips label="الخامات" values={product.materials}/>} {product.colors?.length>0&&<Chips label="الألوان" values={product.colors}/>} {product.finish&&<div className="mt-5 text-sm"><b>التشطيب: </b>{product.finish}</div>}</div></aside></div>
    {canCustomize&&<section id="customize" className="mt-16 rounded-[38px] border border-black/10 bg-white p-6 md:p-10"><div className="max-w-3xl"><div className="text-sm font-bold text-[#8d7657]">تخصيص الموديل</div><h2 className="mt-2 text-3xl font-black">خصص {product.name_ar} لمساحتك</h2><p className="mt-3 text-sm leading-7 text-slate-500">أدخل المقاسات والخامات المطلوبة وارفع صورة أو مخطط. اقتراح AI تصميمي فقط ولا يعتمد السعر النهائي.</p></div><form onSubmit={submitCustomization} className="mt-8 grid gap-5 md:grid-cols-2"><input tabIndex={-1} autoComplete="off" name="website" className="hidden"/>{[["full_name","الاسم","text"],["phone","رقم الجوال","tel"],["email","البريد الإلكتروني","email"],["width_mm","العرض بالملم","number"],["depth_mm","العمق بالملم","number"],["height_mm","الارتفاع بالملم","number"],["color","اللون المطلوب","text"],["wood","الخشب / اللوح","text"],["fabric","القماش / التنجيد","text"]].map(([name,label,type])=><label key={name} className="text-sm font-bold">{label}<input name={name} type={type} className="mt-2 w-full rounded-2xl border border-black/10 bg-[#f7f5f0] px-4 py-3 outline-none focus:border-[#8d7657]"/></label>)}<label className="md:col-span-2 text-sm font-bold">الإكسسوارات والملاحظات<textarea name="notes" rows={4} className="mt-2 w-full rounded-2xl border border-black/10 bg-[#f7f5f0] px-4 py-3 outline-none"/></label><label className="text-sm font-bold">صورة الغرفة<input name="room_photo" type="file" accept="image/jpeg,image/png,image/webp" className="mt-2 block w-full rounded-2xl border border-dashed border-black/20 p-4 text-xs"/></label><label className="text-sm font-bold">مخطط / Plan<input name="plan" type="file" accept="image/jpeg,image/png,image/webp,application/pdf" className="mt-2 block w-full rounded-2xl border border-dashed border-black/20 p-4 text-xs"/></label><label className="md:col-span-2 flex cursor-pointer items-start gap-3 rounded-2xl bg-[#f2eee6] p-5"><input type="checkbox" name="ai_design" value="yes" className="mt-1"/><span><span className="flex items-center gap-2 font-black"><Sparkles className="h-4 w-4"/> صمم هذا الموديل لمساحتي</span><span className="mt-1 block text-xs leading-6 text-slate-500">يُرسل الطلب لمحرك التصميم في منصة المقرن لاقتراح المقاس واللون والخامة والتوزيع وRender تقريبي.</span></span></label>{error&&<div className="md:col-span-2 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}<div className="md:col-span-2"><button disabled={sending} className="rounded-full bg-[#17212a] px-8 py-3.5 text-sm font-black text-white disabled:opacity-50">{sending?"جارٍ الإرسال…":"احصل على عرض سعر"}</button></div></form></section>}
  </main>;
}
function Spec({label,value}:{label:string;value:string}){return <div className="rounded-2xl bg-white p-4"><Ruler className="mb-2 h-4 w-4"/><div className="text-xs text-slate-500">{label}</div><b>{value}</b></div>}
function Chips({label,values}:{label:string;values:string[]}){return <div className="mt-5"><div className="text-xs font-bold text-slate-500">{label}</div><div className="mt-2 flex flex-wrap gap-2">{values.map(v=><span key={v} className="rounded-full bg-white px-3 py-1.5 text-xs font-bold">{v}</span>)}</div></div>}
