import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { Box, Search, Sparkles, Wrench } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";

type MediaItem={type?:string;url?:string;alt?:string};
type Product={product_id:string;public_slug:string;model_code:string;name_ar:string;description:string|null;category_slug:string|null;category_name_ar:string|null;price_with_vat:number;production_history_count:number;media:MediaItem[]|null};
const categories=[["bedrooms","غرف النوم"],["majlis-sofas","المجالس والكنب"],["offices","المكاتب"],["tables","الطاولات"],["chairs","الكراسي"],["storage","الخزائن والتخزين"],["custom","أثاث حسب الطلب"]];
const sar=new Intl.NumberFormat("ar-SA",{style:"currency",currency:"SAR",maximumFractionDigits:2});
const SEARCH_EDGE="https://vmswbmkkgvnjhznxbsdz.supabase.co/functions/v1/storefront-search";
export const Route=createFileRoute("/store/")({component:StoreHome});

function StoreHome(){
 const [products,setProducts]=useState<Product[]>([]),[loading,setLoading]=useState(true),[q,setQ]=useState(""),[category,setCategory]=useState(""),[intent,setIntent]=useState<string|null>(null);
 useEffect(()=>{const p=new URLSearchParams(location.search);setQ(p.get("q")??"");setCategory(p.get("category")??"")},[]);
 useEffect(()=>{let alive=true;setLoading(true);setIntent(null);(async()=>{try{if(q.trim()){const r=await fetch(SEARCH_EDGE,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({q:q.trim()})});const b=await r.json();if(alive){setProducts((b.products??[]) as Product[]);setIntent(b.intent_ar??null)}}else{let query=(supabase as any).from("store_public_catalog").select("*").order("published_at",{ascending:false}).limit(60);if(category)query=query.eq("category_slug",category);const{data}=await query;if(alive)setProducts((data??[]) as Product[])}}finally{if(alive)setLoading(false)}})();return()=>{alive=false}},[q,category]);
 const mostProduced=useMemo(()=>[...products].sort((a,b)=>Number(b.production_history_count)-Number(a.production_history_count)).slice(0,4),[products]);
 const hero=products[0],heroImage=hero?.media?.find(m=>m.type!=="glb"&&m.type!=="usdz")?.url;
 function search(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const value=String(new FormData(e.currentTarget).get("q")??"").trim();setCategory("");setQ(value);history.replaceState(null,"",value?`/store?q=${encodeURIComponent(value)}`:"/store")}
 function chooseCategory(slug:string){setQ("");setCategory(slug);history.replaceState(null,"",`/store?category=${slug}`)}
 return <main>
  <section className="relative isolate overflow-hidden bg-[#17212a] text-white">{heroImage&&<img src={heroImage} alt="مشروع منفذ" className="absolute inset-0 -z-20 h-full w-full object-cover opacity-35"/>}<div className="absolute inset-0 -z-10 bg-gradient-to-l from-[#17212a] via-[#17212a]/90 to-[#17212a]/35"/><div className="mx-auto grid min-h-[610px] max-w-7xl items-center gap-12 px-6 py-20 lg:grid-cols-2"><div><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-4 py-2 text-xs"><Sparkles className="h-4 w-4"/> موديلات مصنعة فعليًا ومعتمدة</div><h1 className="max-w-3xl text-4xl font-black leading-[1.3] sm:text-6xl">أثاث صُمم وصُنّع في مصنع المقرن</h1><p className="mt-6 max-w-xl text-base leading-8 text-white/75">تصفح موديلات خرجت من خطوط إنتاج المصنع فعلًا، مع سعر لا يظهر إلا بعد اجتياز الجودة واعتماد إدارة المنصة.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#models" className="rounded-full bg-white px-6 py-3 text-sm font-black text-[#17212a]">تصفح الموديلات</a><a href="#custom" className="rounded-full border border-white/30 px-6 py-3 text-sm font-bold">اطلب تصميمك الخاص</a></div></div><div className="hidden lg:block"><div className="mr-auto max-w-sm rounded-[34px] border border-white/15 bg-white/10 p-6 backdrop-blur"><div className="text-xs text-white/60">كيف يصل المنتج للمتجر؟</div><div className="mt-4 space-y-4 text-sm"><div>01 — تصنيع فعلي بالمصنع</div><div>02 — اجتياز الجودة QC</div><div>03 — مراجعة المحتوى والصور</div><div>04 — اعتماد المدير للسعر</div><div>05 — اعتماد النشر</div></div></div></div></div></section>
  <section id="search" className="mx-auto max-w-7xl px-6 py-10"><form onSubmit={search} className="flex flex-col gap-3 rounded-[28px] border border-black/10 bg-white p-3 shadow-sm md:flex-row"><div className="flex flex-1 items-center gap-3 px-3"><Search className="h-5 w-5 text-[#8d7657]"/><input name="q" defaultValue={q} className="w-full bg-transparent py-3 outline-none" placeholder="مثال: مكتب مدير أسود 240 سم مع أدراج جانبية"/></div><button className="rounded-2xl bg-[#17212a] px-7 py-3 text-sm font-bold text-white">بحث ذكي في موديلات المصنع</button></form>{intent&&<div className="mt-3 rounded-xl bg-[#eee9df] px-4 py-3 text-xs text-slate-600"><b>فهم البحث:</b> {intent}</div>}<div className="mt-4 flex gap-2 overflow-x-auto pb-2">{categories.map(([slug,name])=><button key={slug} onClick={()=>chooseCategory(slug)} className="whitespace-nowrap rounded-full border border-black/10 bg-white px-4 py-2 text-xs font-bold hover:border-[#8d7657]">{name}</button>)}</div></section>
  <section id="models" className="mx-auto max-w-7xl px-6 py-10"><div className="text-sm font-bold text-[#8d7657]">من إنتاج مصنعنا</div><h2 className="mt-1 text-3xl font-black">موديلات جاهزة للاختيار والتخصيص</h2>{loading?<div className="mt-8 text-sm text-slate-500">جارٍ البحث في موديلات المصنع…</div>:products.length?<div className="mt-8 grid gap-6 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{products.map(p=><ProductCard key={p.product_id} product={p}/>)}</div>:<div className="mt-8 rounded-[32px] border border-dashed border-black/20 bg-white p-12 text-center"><Wrench className="mx-auto h-10 w-10 text-[#8d7657]"/><h3 className="mt-4 text-xl font-black">لا توجد موديلات منشورة مطابقة</h3><p className="mx-auto mt-2 max-w-xl text-sm leading-7 text-slate-500">المتجر لا يعرض أي منتج قبل اكتمال التصنيع، نجاح الجودة، واعتماد السعر والنشر من مدير المنصة.</p></div>}</section>
  <section className="mx-auto max-w-7xl px-6 py-10"><div className="rounded-[36px] bg-[#e9e4da] p-8 md:p-12"><div className="text-sm font-bold text-[#8d7657]">الأكثر تصنيعًا</div><h2 className="mt-1 text-3xl font-black">موديلات أثبتت حضورها في المصنع</h2>{mostProduced.length>0&&<div className="mt-8 grid gap-4 md:grid-cols-4">{mostProduced.map((p,i)=><Link key={p.product_id} to="/store/$slug" params={{slug:p.public_slug}} className="rounded-2xl bg-white p-5"><div className="text-3xl font-black text-[#8d7657]">0{i+1}</div><div className="mt-4 font-black">{p.name_ar}</div><div className="mt-1 text-xs text-slate-500">تم تصنيعه {p.production_history_count} مرة</div></Link>)}</div>}</div></section>
  <section id="projects" className="mx-auto max-w-7xl px-6 py-10"><div className="grid gap-5 md:grid-cols-3">{categories.slice(0,6).map(([slug,name])=><button key={slug} onClick={()=>{chooseCategory(slug);location.hash="models"}} className="flex min-h-40 items-end rounded-[28px] bg-[#17212a] p-6 text-right text-xl font-black text-white transition hover:-translate-y-1">{name}</button>)}</div></section>
  <section id="custom" className="mx-auto max-w-7xl px-6 py-10"><div className="rounded-[40px] border border-black/10 bg-white p-8 md:p-14"><div className="max-w-2xl"><div className="text-sm font-bold text-[#8d7657]">أثاث حسب الطلب</div><h2 className="mt-2 text-3xl font-black md:text-4xl">لديك صورة أو مساحة مختلفة؟ ابدأ من أقرب موديل.</h2><p className="mt-5 leading-8 text-slate-500">اختر موديلًا قابلًا للتخصيص، أدخل أبعاد المساحة والخامات المطلوبة وارفع صورة أو مخطط. يصل الطلب مباشرة لمنصة المقرن، والسعر النهائي يبقى بانتظار اعتماد المصنع.</p></div></div></section>
 </main>
}
function ProductCard({product}:{product:Product}){const image=product.media?.find(m=>m.type!=="glb"&&m.type!=="usdz")?.url;return <Link to="/store/$slug" params={{slug:product.public_slug}} className="group overflow-hidden rounded-[28px] border border-black/10 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div className="relative aspect-[4/3] overflow-hidden bg-[#e9e4da]">{image?<img src={image} alt={product.name_ar} className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/>:<div className="flex h-full items-center justify-center"><Box className="h-14 w-14 text-black/20"/></div>}<span className="absolute right-3 top-3 rounded-full bg-white/90 px-3 py-1 text-[11px] font-bold">{product.model_code}</span></div><div className="p-5"><div className="text-xs font-semibold text-[#8d7657]">{product.category_name_ar??"من إنتاج مصنعنا"}</div><h3 className="mt-1 text-lg font-black">{product.name_ar}</h3><p className="mt-2 line-clamp-2 text-sm leading-6 text-slate-500">{product.description??"موديل مصنع ومعتمد من مصنع المقرن."}</p><div className="mt-4 flex items-end justify-between gap-3"><div><div className="text-xs text-slate-500">شامل الضريبة</div><div className="text-lg font-black">{sar.format(Number(product.price_with_vat))}</div></div><div className="text-xs text-slate-500">صُنّع {product.production_history_count} مرة</div></div></div></Link>}
