import { useEffect, useState } from "react";
import { Save, Stamp } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/lib/auth";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Checkbox } from "@/components/ui/checkbox";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

type Form={enabled:boolean;apply_platform_ui:boolean;apply_generated_documents:boolean;apply_store_media:boolean;apply_ai_outputs:boolean;apply_extracted_pdf_media:boolean;watermark_text:string;logo_url:string;opacity:number;position:string};
const initial:Form={enabled:true,apply_platform_ui:true,apply_generated_documents:true,apply_store_media:true,apply_ai_outputs:true,apply_extracted_pdf_media:true,watermark_text:"مصنع المقرن للأثاث والديكور",logo_url:"",opacity:.10,position:"center"};
export function WatermarkSettings(){
 const {user}=useAuth(); const [form,setForm]=useState<Form>(initial); const [saving,setSaving]=useState(false);
 useEffect(()=>{void (async()=>{if(!user?.companyId)return;const {data}=await (supabase as any).from("watermark_settings").select("*").eq("company_id",user.companyId).maybeSingle();if(data)setForm({...initial,...data,logo_url:data.logo_url??""})})()},[user?.companyId]);
 async function save(){if(!user?.companyId)return;setSaving(true);const {error}=await (supabase as any).from("watermark_settings").upsert({company_id:user.companyId,...form,logo_url:form.logo_url||null,updated_by:user.id,updated_at:new Date().toISOString()},{onConflict:"company_id"});setSaving(false);if(error)toast.error(error.message);else toast.success("تم اعتماد إعدادات العلامة المائية");}
 const toggle=(k:keyof Form)=>(v:boolean|string)=>setForm(f=>({...f,[k]:typeof v==="boolean"?v:v==="true"}));
 return <Card className="shadow-card"><CardHeader><CardTitle className="flex items-center gap-2"><Stamp className="h-5 w-5 text-primary"/>العلامة المائية الشاملة</CardTitle><CardDescription>تطبق على واجهة المنصة والمستندات والمخرجات الذكية وصور المتجر والصور المستخرجة من PDF، مع بقاء الأصل الخاص بدون تعديل.</CardDescription></CardHeader><CardContent className="space-y-5"><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3"><Check label="تفعيل العلامة المائية" checked={form.enabled} onChange={v=>toggle("enabled")(v)}/><Check label="داخل لوحات المنصة" checked={form.apply_platform_ui} onChange={v=>toggle("apply_platform_ui")(v)}/><Check label="المستندات المولدة" checked={form.apply_generated_documents} onChange={v=>toggle("apply_generated_documents")(v)}/><Check label="صور المتجر العامة" checked={form.apply_store_media} onChange={v=>toggle("apply_store_media")(v)}/><Check label="مخرجات الذكاء الاصطناعي" checked={form.apply_ai_outputs} onChange={v=>toggle("apply_ai_outputs")(v)}/><Check label="صور المنتجات المستخرجة من PDF" checked={form.apply_extracted_pdf_media} onChange={v=>toggle("apply_extracted_pdf_media")(v)}/></div><div className="grid gap-4 md:grid-cols-2"><div className="space-y-2"><Label>نص العلامة</Label><Input value={form.watermark_text} onChange={e=>setForm(f=>({...f,watermark_text:e.target.value}))}/></div><div className="space-y-2"><Label>رابط الشعار اختياري</Label><Input dir="ltr" value={form.logo_url} onChange={e=>setForm(f=>({...f,logo_url:e.target.value}))}/></div><div className="space-y-2"><Label>الموضع</Label><Select value={form.position} onValueChange={v=>setForm(f=>({...f,position:v}))}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="center">وسط</SelectItem><SelectItem value="diagonal">مائل</SelectItem><SelectItem value="repeat">متكرر</SelectItem><SelectItem value="bottom_right">أسفل اليمين</SelectItem></SelectContent></Select></div><div className="space-y-2"><Label>الشفافية: {Math.round(form.opacity*100)}%</Label><Input type="range" min="0.02" max="0.5" step="0.01" value={form.opacity} onChange={e=>setForm(f=>({...f,opacity:Number(e.target.value)}))}/></div></div><div className="flex justify-end"><Button onClick={save} disabled={saving} className="gap-2"><Save className="h-4 w-4"/>حفظ إعدادات العلامة</Button></div></CardContent></Card>;
}
function Check({label,checked,onChange}:{label:string;checked:boolean;onChange:(v:boolean)=>void}){return <label className="flex items-center gap-3 rounded-xl border p-3 text-sm font-medium"><Checkbox checked={checked} onCheckedChange={v=>onChange(v===true)}/>{label}</label>}
