import { useEffect, useState } from "react";
import { LockKeyhole, Save, Stamp } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/lib/auth";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Checkbox } from "@/components/ui/checkbox";

type Form={enabled:boolean;apply_platform_ui:boolean;apply_generated_documents:boolean;apply_store_media:boolean;apply_ai_outputs:boolean;apply_extracted_pdf_media:boolean;watermark_text:string;logo_url:string;opacity:number;position:string};
const FACTORY_LOGO="/brand/almugren-furniture-logo.jpeg";
const initial:Form={enabled:true,apply_platform_ui:true,apply_generated_documents:true,apply_store_media:true,apply_ai_outputs:true,apply_extracted_pdf_media:true,watermark_text:"",logo_url:FACTORY_LOGO,opacity:.14,position:"center"};
export function WatermarkSettings(){
 const {user,hasRole}=useAuth(); const [form,setForm]=useState<Form>(initial); const [saving,setSaving]=useState(false); const canManage=hasRole("factory_owner");
 useEffect(()=>{void (async()=>{if(!user?.companyId)return;const {data}=await (supabase as any).from("watermark_settings").select("*").eq("company_id",user.companyId).maybeSingle();if(data)setForm({...initial,...data,watermark_text:"",enabled:true,apply_platform_ui:true,apply_generated_documents:true,apply_store_media:true,apply_ai_outputs:true,apply_extracted_pdf_media:true,logo_url:data.logo_url??FACTORY_LOGO,opacity:.14,position:"center"})})()},[user?.companyId]);
 async function save(){if(!user?.companyId)return;if(!canManage){toast.error("إعدادات العلامة المائية محمية ولا يمكن تغييرها إلا من مالك المصنع");return;}setSaving(true);const {error}=await (supabase as any).from("watermark_settings").upsert({company_id:user.companyId,...form,watermark_text:"",enabled:true,apply_platform_ui:true,apply_generated_documents:true,apply_store_media:true,apply_ai_outputs:true,apply_extracted_pdf_media:true,logo_url:form.logo_url||FACTORY_LOGO,opacity:.14,position:"center",updated_by:user.id,updated_at:new Date().toISOString()},{onConflict:"company_id"});setSaving(false);if(error)toast.error(error.message);else toast.success("تم اعتماد إعدادات العلامة المائية");}
 const toggle=(k:keyof Form)=>(v:boolean|string)=>{if(!canManage)return;setForm(f=>({...f,[k]:typeof v==="boolean"?v:v==="true"}))};
 const disabled=!canManage;
 return <Card className="shadow-card"><CardHeader><CardTitle className="flex items-center gap-2"><Stamp className="h-5 w-5 text-primary"/>العلامة المائية الشاملة</CardTitle><CardDescription>الشعار المعتمد فقط هو العلامة المائية الثابتة على المستندات المولدة. تغيير إعدادات الهوية والعلامة المائية متاح لمالك المصنع فقط.</CardDescription></CardHeader><CardContent className="space-y-5">{!canManage&&<div className="flex items-center gap-2 rounded-xl border border-amber-500/30 bg-amber-500/5 p-3 text-sm"><LockKeyhole className="h-4 w-4"/><span>هذه الإعدادات للعرض فقط. لا يمكن تعديلها إلا بحساب مالك المصنع.</span></div>}<div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3"><Check label="تفعيل العلامة المائية — إلزامي" checked={true} disabled onChange={()=>{}}/><Check label="داخل لوحات المنصة — إلزامي" checked={true} disabled onChange={()=>{}}/><Check label="المستندات المولدة — إلزامي" checked={true} disabled onChange={()=>{}}/><Check label="صور المتجر العامة — إلزامي" checked={true} disabled onChange={()=>{}}/><Check label="مخرجات الذكاء الاصطناعي — إلزامي" checked={true} disabled onChange={()=>{}}/><Check label="صور المنتجات المستخرجة من PDF — إلزامي" checked={true} disabled onChange={()=>{}}/></div><div className="grid gap-4 md:grid-cols-2"><div className="space-y-2"><Label>شعار العلامة المائية</Label><Input disabled={disabled} dir="ltr" value={form.logo_url} onChange={e=>setForm(f=>({...f,logo_url:e.target.value}))}/><p className="text-xs text-muted-foreground">الافتراضي: شعار مصنع المقرن المعتمد.</p></div><div className="rounded-xl border bg-muted/30 p-3 text-sm font-medium">علامة مائية موحّدة: الشعار فقط · حجم متوسط · شفافية 14%</div></div><div className="flex justify-end"><Button onClick={save} disabled={saving||!canManage} className="gap-2"><Save className="h-4 w-4"/>حفظ إعدادات العلامة</Button></div></CardContent></Card>;
}
function Check({label,checked,disabled=false,onChange}:{label:string;checked:boolean;disabled?:boolean;onChange:(v:boolean)=>void}){return <label className="flex items-center gap-3 rounded-xl border p-3 text-sm font-medium"><Checkbox disabled={disabled} checked={checked} onCheckedChange={v=>onChange(v===true)}/>{label}</label>}
