import { useEffect, useState } from "react";
import { LockKeyhole, Save, Stamp } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/lib/auth";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Checkbox } from "@/components/ui/checkbox";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

type Form={enabled:boolean;apply_platform_ui:boolean;apply_generated_documents:boolean;apply_store_media:boolean;apply_ai_outputs:boolean;apply_extracted_pdf_media:boolean;watermark_text:string;logo_url:string;opacity:number;position:string};
const FACTORY_LOGO="/brand/almugren-furniture-logo.jpeg";
const initial:Form={enabled:true,apply_platform_ui:true,apply_generated_documents:true,apply_store_media:true,apply_ai_outputs:true,apply_extracted_pdf_media:true,watermark_text:"مصنع المقرن للأثاث والديكور",logo_url:FACTORY_LOGO,opacity:.10,position:"center"};
export function WatermarkSettings(){
 const {user,hasRole}=useAuth(); const [form,setForm]=useState<Form>(initial); const [saving,setSaving]=useState(false); const canManage=hasRole("factory_owner");
 useEffect(()=>{void (async()=>{if(!user?.companyId)return;const {data}=await (supabase as any).from("watermark_settings").select("*").eq("company_id",user.companyId).maybeSingle();if(data)setForm({...initial,...data,enabled:true,apply_generated_documents:true,logo_url:data.logo_url??FACTORY_LOGO})})()},[user?.companyId]);
 async function save(){if(!user?.companyId)return;if(!canManage){toast.error("إعدادات العلامة المائية محمية ولا يمكن تغييرها إلا من مالك المصنع");return;}setSaving(true);const {error}=await (supabase as any).from("watermark_settings").upsert({company_id:user.companyId,...form,enabled:true,apply_generated_documents:true,logo_url:form.logo_url||FACTORY_LOGO,updated_by:user.id,updated_at:new Date().toISOString()},{onConflict:"company_id"});setSaving(false);if(error)toast.error(error.message);else toast.success("تم اعتماد إعدادات العلامة المائية");}
 const toggle=(k:keyof Form)=>(v:boolean|string)=>{if(!canManage)return;setForm(f=>({...f,[k]:typeof v==="boolean"?v:v==="true"}))};
 const disabled=!canManage;
 return <Card className="shadow-card"><CardHeader><CardTitle className="flex items-center gap-2"><Stamp className="h-5 w-5 text-primary"/>العلامة المائية الشاملة</CardTitle><CardDescription>شعار مصنع المقرن علامة مائية ثابتة على المستندات المولدة. تغيير إعدادات الهوية والعلامة المائية متاح لمالك المصنع فقط.</CardDescription></CardHeader><CardContent className="space-y-5">{!canManage&&<div className="flex items-center gap-2 rounded-xl border border-amber-500/30 bg-amber-500/5 p-3 text-sm"><LockKeyhole className="h-4 w-4"/><span>هذه الإعدادات للعرض فقط. لا يمكن تعديلها إلا بحساب مالك المصنع.</span></div>}<div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3"><Check label="تفعيل العلامة المائية — إلزامي" checked={true} disabled onChange={()=>{}}/><Check label="داخل لوحات المنصة" checked={form.apply_platform_ui} disabled={disabled} onChange={v=>toggle("apply_platform_ui")(v)}/><Check label="المستندات المولدة — إلزامي" checked={true} disabled onChange={()=>{}}/><Check label="صور المتجر العامة" checked={form.apply_store_media} disabled={disabled} onChange={v=>toggle("apply_store_media")(v)}/><Check label="مخرجات الذكاء الاصطناعي" checked={form.apply_ai_outputs} disabled={disabled} onChange={v=>toggle("apply_ai_outputs")(v)}/><Check label="صور المنتجات المستخرجة من PDF" checked={form.apply_extracted_pdf_media} disabled={disabled} onChange={v=>toggle("apply_extracted_pdf_media")(v)}/></div><div className="grid gap-4 md:grid-cols-2"><div className="space-y-2"><Label>نص العلامة</Label><Input disabled={disabled} value={form.watermark_text} onChange={e=>setForm(f=>({...f,watermark_text:e.target.value}))}/></div><div className="space-y-2"><Label>شعار العلامة المائية</Label><Input disabled={disabled} dir="ltr" value={form.logo_url} onChange={e=>setForm(f=>({...f,logo_url:e.target.value}))}/><p className="text-xs text-muted-foreground">الافتراضي: شعار مصنع المقرن المعتمد.</p></div><div className="space-y-2"><Label>الموضع</Label><Select disabled={disabled} value={form.position} onValueChange={v=>setForm(f=>({...f,position:v}))}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="center">وسط</SelectItem><SelectItem value="diagonal">مائل</SelectItem><SelectItem value="repeat">متكرر</SelectItem><SelectItem value="bottom_right">أسفل اليمين</SelectItem></SelectContent></Select></div><div className="space-y-2"><Label>الشفافية: {Math.round(form.opacity*100)}%</Label><Input disabled={disabled} type="range" min="0.02" max="0.5" step="0.01" value={form.opacity} onChange={e=>setForm(f=>({...f,opacity:Number(e.target.value)}))}/></div></div><div className="flex justify-end"><Button onClick={save} disabled={saving||!canManage} className="gap-2"><Save className="h-4 w-4"/>حفظ إعدادات العلامة</Button></div></CardContent></Card>;
}
function Check({label,checked,disabled=false,onChange}:{label:string;checked:boolean;disabled?:boolean;onChange:(v:boolean)=>void}){return <label className="flex items-center gap-3 rounded-xl border p-3 text-sm font-medium"><Checkbox disabled={disabled} checked={checked} onCheckedChange={v=>onChange(v===true)}/>{label}</label>}
