import { createFileRoute, Link } from "@tanstack/react-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { CheckCircle2, CircleDollarSign, Eye, ImageIcon, ShieldCheck } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/lib/auth";

type Product = any; type Media = any; type Design = any;
export const Route = createFileRoute("/_authenticated/store-admin")({ head:()=>({meta:[{title:"اعتماد المتجر · منصة المقرن"}]}), component:StoreAdmin });

function StoreAdmin(){
 const {user,isAdmin}=useAuth(); const [products,setProducts]=useState<Product[]>([]);const [media,setMedia]=useState<Media[]>([]);const [designs,setDesigns]=useState<Design[]>([]);const [qc,setQc]=useState<Record<string,string>>({});const [busy,setBusy]=useState<string|null>(null);const [message,setMessage]=useState<string|null>(null);
 const load=useCallback(async()=>{if(!user?.companyId)return;const db=supabase as any;const [{data:p},{data:m},{data:d}]=await Promise.all([db.from("store_products").select("*").eq("company_id",user.companyId).order("created_at",{ascending:false}),db.from("store_product_media").select("*").eq("company_id",user.companyId).order("sort_order"),db.from("design_assets").select("id,sku,name_ar,category,thumbnail_url").eq("company_id",user.companyId).eq("active",true).order("created_at",{ascending:false}).limit(100)]);setProducts(p??[]);setMedia(m??[]);setDesigns(d??[]);const ids=(p??[]).map((x:any)=>x.source_manufacturing_order_id).filter(Boolean);if(ids.length){const {data:q}=await db.from("quality_inspections").select("manufacturing_order_id,result,inspected_at").in("manufacturing_order_id",ids).order("inspected_at",{ascending:false});const map:Record<string,string>={};for(const row of q??[])if(!map[row.manufacturing_order_id])map[row.manufacturing_order_id]=row.result;setQc(map)}} ,[user?.companyId]);
 useEffect(()=>{void load()},[load]);
 const stats=useMemo(()=>({all:products.length,content:products.filter(p=>p.content_review_status==="approved").length,price:products.filter(p=>p.price_approval_status==="approved").length,published:products.filter(p=>p.status==="published"&&p.visibility==="public").length}),[products]);
 if(!isAdmin)return <div dir="rtl" className="mx-auto max-w-3xl"><h1 className="text-2xl font-bold">مركز اعتماد المتجر</h1><p className="mt-3 text-muted-foreground">هذه الصفحة مخصصة لمالك المصنع أو المدير العام أو مدير النظام.</p></div>;
 async function review(productId:string,type:string,decision:string,price?:number){setBusy(`${productId}:${type}`);setMessage(null);const {error}=await (supabase as any).rpc("review_store_product",{p_product_id:productId,p_approval_type:type,p_decision:decision,p_price_before_vat:price??null,p_note:null});setBusy(null);if(error){setMessage(error.message);return}await load()}
 async function approveMedia(id:string,approved:boolean){setBusy(id);const {error}=await (supabase as any).rpc("approve_store_product_media",{p_media_id:id,p_approved:approved,p_note:null});setBusy(null);if(error)setMessage(error.message);else await load()}
 async function attachDesign(productId:string,designId:string){if(!designId)return;setBusy(`${productId}:design`);const {error}=await (supabase as any).rpc("attach_store_design_asset",{p_product_id:productId,p_design_asset_id:designId});setBusy(null);if(error)setMessage(error.message);else await load()}
 return <div dir="rtl" className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><div className="text-xs font-medium uppercase tracking-widest text-muted-foreground">منصة المقرن</div><h1 className="mt-1 text-3xl font-bold">مركز اعتماد منتجات المتجر</h1><p className="mt-2 text-sm text-muted-foreground">التصنيع → الجودة → المحتوى → اعتماد السعر → اعتماد النشر</p></div><Link to="/store" target="_blank" className="inline-flex items-center gap-2 rounded-full border bg-card px-5 py-3 text-sm font-bold"><Eye className="h-4 w-4"/>معاينة المتجر</Link></div>
 {message&&<div className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700">{message}</div>}
 <div className="grid gap-4 sm:grid-cols-4"><Stat label="مرشحو المتجر" value={stats.all} icon={<ShieldCheck className="h-5 w-5"/>}/><Stat label="محتوى معتمد" value={stats.content} icon={<CheckCircle2 className="h-5 w-5"/>}/><Stat label="سعر معتمد" value={stats.price} icon={<CircleDollarSign className="h-5 w-5"/>}/><Stat label="منشور" value={stats.published} icon={<Eye className="h-5 w-5"/>}/></div>
 <div className="space-y-5">{products.length===0&&<div className="rounded-3xl border border-dashed bg-card p-12 text-center"><h2 className="text-xl font-bold">لا توجد موديلات مرشحة بعد</h2><p className="mt-2 text-sm text-muted-foreground">سيظهر الموديل تلقائيًا عندما يصل أمر التصنيع إلى Ready for Delivery أو Delivered.</p></div>}{products.map(p=>{const pm=media.filter(m=>m.product_id===p.id);const q=p.source_manufacturing_order_id?(qc[p.source_manufacturing_order_id]??"لا يوجد فحص"):"لا يوجد أمر تصنيع";const prior=Number(p.pricing_snapshot?.previous_sale_price??0);const ready=q==="pass"&&p.content_review_status==="approved"&&p.price_approval_status==="approved";return <article key={p.id} className="overflow-hidden rounded-3xl border bg-card shadow-sm"><div className="grid lg:grid-cols-[250px_1fr]"><div className="min-h-56 bg-muted p-4">{pm.find(m=>m.approved_for_public&&["factory_photo","design_image","design_render"].includes(m.media_type))?.media_url?<img src={pm.find(m=>m.approved_for_public&&["factory_photo","design_image","design_render"].includes(m.media_type)).media_url} alt={p.name_ar} className="h-full w-full rounded-2xl object-cover"/>:<div className="flex h-full min-h-52 items-center justify-center rounded-2xl border border-dashed"><ImageIcon className="h-10 w-10 text-muted-foreground"/></div>}</div><div className="p-6"><div className="flex flex-wrap justify-between gap-4"><div><div className="text-xs font-bold text-primary">{p.model_code}</div><h2 className="mt-1 text-2xl font-bold">{p.name_ar}</h2><div className="mt-2 text-xs text-muted-foreground">QC: <b className={q==="pass"?"text-emerald-600":"text-amber-600"}>{q}</b> • سجل الإنتاج: {p.production_history_count}</div></div><span className={`h-fit rounded-full px-4 py-2 text-xs font-bold ${p.status==="published"?"bg-emerald-100 text-emerald-800":"bg-amber-100 text-amber-800"}`}>{p.status==="published"?"منشور":"مراجعة داخلية"}</span></div>
 <div className="mt-5 grid gap-3 sm:grid-cols-3"><Value label="تكلفة التنفيذ المسجلة" value={`${Number(p.execution_cost).toLocaleString("ar-SA")} ر.س`}/><Value label="آخر سعر بيع — مرجع فقط" value={`${prior.toLocaleString("ar-SA")} ر.س`}/><Value label="سعر المدير شامل الضريبة" value={`${Number(p.manager_price_with_vat).toLocaleString("ar-SA")} ر.س`}/></div>
 <div className="mt-5 grid gap-4 xl:grid-cols-3"><Action title="1. المحتوى" subtitle={`الحالة: ${p.content_review_status}`}><button disabled={busy!==null} onClick={()=>review(p.id,"content","approved")} className="rounded-lg bg-emerald-700 px-3 py-2 text-xs font-bold text-white">اعتماد</button><button disabled={busy!==null} onClick={()=>review(p.id,"content","rejected")} className="rounded-lg bg-red-50 px-3 py-2 text-xs font-bold text-red-700">رفض</button></Action><PriceAction p={p} disabled={busy!==null} onApprove={(price)=>review(p.id,"price","approved",price)} onReject={()=>review(p.id,"price","rejected")}/><Action title="3. النشر" subtitle={ready?"جاهز لاعتماد النشر":"يلزم QC ناجح + محتوى + سعر"}><button disabled={!ready||busy!==null} onClick={()=>review(p.id,"publish","approved")} className="rounded-lg bg-primary px-3 py-2 text-xs font-bold text-primary-foreground disabled:opacity-30">نشر</button><button disabled={busy!==null} onClick={()=>review(p.id,"publish","rejected")} className="rounded-lg bg-red-50 px-3 py-2 text-xs font-bold text-red-700">إيقاف</button></Action></div>
 <div className="mt-5 grid gap-4 lg:grid-cols-2"><div className="rounded-2xl bg-muted p-4"><b>ربط التصميم</b><div className="mt-3 flex gap-2"><select defaultValue={p.design_asset_id??""} onChange={e=>void attachDesign(p.id,e.target.value)} className="min-w-0 flex-1 rounded-lg border bg-background px-3 py-2 text-sm"><option value="">اختر تصميمًا معتمدًا...</option>{designs.map(d=><option key={d.id} value={d.id}>{d.sku} — {d.name_ar}</option>)}</select></div><p className="mt-2 text-[11px] text-muted-foreground">ينقل الأبعاد والصورة وGLB/USZD كوسائط معلقة؛ لا تصبح عامة قبل اعتماد المدير.</p></div><div className="rounded-2xl bg-muted p-4"><b>وسائط المنتج</b><div className="mt-3 space-y-2">{pm.length?pm.map(m=><div key={m.id} className="flex items-center justify-between gap-2 rounded-lg bg-background p-2 text-xs"><span className="truncate">{m.media_type} • {m.approved_for_public?"عام":"بانتظار الاعتماد"}</span><button disabled={busy!==null} onClick={()=>approveMedia(m.id,!m.approved_for_public)} className="rounded border px-2 py-1 font-bold">{m.approved_for_public?"إخفاء":"اعتماد"}</button></div>):<span className="text-xs text-muted-foreground">لا توجد وسائط مربوطة.</span>}</div></div></div>
 </div></div></article>})}</div></div>
}
function Stat({label,value,icon}:{label:string;value:number;icon:React.ReactNode}){return <div className="rounded-2xl border bg-card p-5"><div className="flex items-center justify-between text-primary">{icon}<span className="text-2xl font-bold text-foreground">{value}</span></div><div className="mt-3 text-xs font-bold text-muted-foreground">{label}</div></div>}
function Value({label,value}:{label:string;value:string}){return <div className="rounded-2xl bg-muted p-4"><div className="text-[11px] font-bold text-muted-foreground">{label}</div><div className="mt-1 font-bold">{value}</div></div>}
function Action({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <div className="rounded-2xl border p-4"><b>{title}</b><div className="mt-1 text-xs text-muted-foreground">{subtitle}</div><div className="mt-4 flex gap-2">{children}</div></div>}
function PriceAction({p,disabled,onApprove,onReject}:{p:any;disabled:boolean;onApprove:(n:number)=>void;onReject:()=>void}){const [price,setPrice]=useState(String(Number(p.manager_price_before_vat)||""));return <div className="rounded-2xl border p-4"><b>2. السعر</b><div className="mt-1 text-xs text-muted-foreground">السعر السابق مرجع فقط</div><input value={price} onChange={e=>setPrice(e.target.value)} type="number" min="1" step="0.01" placeholder="السعر قبل VAT" className="mt-3 w-full rounded-lg border bg-background px-3 py-2 text-sm"/><div className="mt-2 flex gap-2"><button disabled={disabled||Number(price)<=0} onClick={()=>onApprove(Number(price))} className="rounded-lg bg-foreground px-3 py-2 text-xs font-bold text-background disabled:opacity-30">اعتماد السعر</button><button disabled={disabled} onClick={onReject} className="rounded-lg bg-red-50 px-3 py-2 text-xs font-bold text-red-700">رفض</button></div></div>}
