// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'

const PRODUCTION_SUPABASE_URL = 'https://vmswbmkkgvnjhznxbsdz.supabase.co';
const PRODUCTION_SUPABASE_PUBLISHABLE_KEY = 'sb_publishable_vn2uBc-OOKQaXAGE3Q9Lxw_ydDT1Cun';
const STAGING_SUPABASE_URL = 'https://selljopynsmecxqzgpra.supabase.co';
const STAGING_SUPABASE_PUBLISHABLE_KEY = 'sb_publishable_n0T9ibtda16AK6QDDV1uhA_g6u6abda';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function isProductionHostname(hostname: string): boolean {
  const value = hostname.toLowerCase();
  return value === 'almuqrinfurniturefactory.com'
    || value === 'www.almuqrinfurniturefactory.com'
    || value === 'platform.almuqrinfurniturefactory.com'
    || value === 'almuqrin-ff-platform.vercel.app'
    || value === 'almuqrin-ff-platform-git-main-almuqrinfactory.vercel.app';
}

function isPreviewHostname(hostname: string): boolean {
  const value = hostname.toLowerCase();
  return value.endsWith('.vercel.app') && !isProductionHostname(value);
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined);
    if (init?.headers) new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) headers.delete('Authorization');
    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(async ({ next }) => {
  const request = getRequest();
  if (!request?.headers) throw new Error('Unauthorized: No request headers available');

  const host = request.headers.get('x-forwarded-host') || request.headers.get('host') || '';
  const preview = process.env['VERCEL_ENV'] === 'preview' || isPreviewHostname(host.split(':')[0] || '');
  const SUPABASE_URL = preview ? STAGING_SUPABASE_URL : PRODUCTION_SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = preview ? STAGING_SUPABASE_PUBLISHABLE_KEY : PRODUCTION_SUPABASE_PUBLISHABLE_KEY;

  const authHeader = request.headers.get('authorization');
  if (!authHeader?.startsWith('Bearer ')) throw new Error('Unauthorized: No valid authorization header provided');
  const token = authHeader.slice(7);
  if (!token || token.split('.').length !== 3) throw new Error('Unauthorized: Invalid token');

  const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: { fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY), headers: { Authorization: `Bearer ${token}` } },
    auth: { storage: undefined, persistSession: false, autoRefreshToken: false },
  });

  const { data, error } = await supabase.auth.getClaims(token);
  if (error || !data?.claims?.sub) throw new Error('Unauthorized: Invalid token');
  const userId = data.claims.sub;
  const { data: profile, error: profileError } = await supabase.from('profiles').select('company_id, is_active').eq('id', userId).maybeSingle();
  if (profileError) throw new Error(`Unauthorized: Profile lookup failed (${profileError.code || 'unknown'})`);
  if (!profile?.is_active || !profile.company_id) throw new Error('Unauthorized: Account is disabled or unassigned');
  const { data: effectiveRole, error: roleError } = await supabase.from('user_roles').select('id').eq('user_id', userId).eq('company_id', profile.company_id).limit(1).maybeSingle();
  if (roleError) throw new Error(`Unauthorized: Role lookup failed (${roleError.code || 'unknown'})`);
  if (!effectiveRole) throw new Error('Unauthorized: No active company role');

  return next({ context: { supabase, userId, claims: data.claims } });
});
