// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const PRODUCTION_SUPABASE_URL = 'https://vmswbmkkgvnjhznxbsdz.supabase.co';
const STAGING_SUPABASE_URL = 'https://selljopynsmecxqzgpra.supabase.co';

function resolveSupabaseUrl(value: string | undefined): string {
  const fallback = process.env['VERCEL_ENV'] === 'preview' ? STAGING_SUPABASE_URL : PRODUCTION_SUPABASE_URL;
  if (process.env['VERCEL_ENV'] === 'preview') return STAGING_SUPABASE_URL;

  const candidate = value?.trim().replace(/^(['"])(.*)\1$/, '$2') || fallback;
  try {
    const url = new URL(candidate);
    if ((url.protocol === 'https:' || url.protocol === 'http:') && url.hostname.endsWith('.supabase.co')) return url.origin;
  } catch {}
  console.warn('[Supabase] Invalid SUPABASE_URL; using the approved environment URL.');
  return fallback;
}

function createSupabaseAdminClient() {
  // Preview is forced to the isolated Staging URL. A Production service-role key therefore cannot target Production from Preview.
  const SUPABASE_URL = resolveSupabaseUrl(process.env['SUPABASE_URL']);
  const SUPABASE_SERVICE_ROLE_KEY = process.env['SUPABASE_SERVICE_ROLE_KEY'];

  if (!SUPABASE_SERVICE_ROLE_KEY) {
    const message = 'Missing Supabase environment variable: SUPABASE_SERVICE_ROLE_KEY. Configure a Staging-only credential for Preview.';
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    auth: { storage: undefined, persistSession: false, autoRefreshToken: false, detectSessionInUrl: false },
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
