// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Public browser configuration only. Authorization remains enforced by RLS.
// Server/service credentials must never be added here.
const PRODUCTION_SUPABASE_URL = 'https://vmswbmkkgvnjhznxbsdz.supabase.co';
const PRODUCTION_SUPABASE_PUBLISHABLE_KEY = 'sb_publishable_vn2uBc-OOKQaXAGE3Q9Lxw_ydDT1Cun';
const STAGING_SUPABASE_URL = 'https://selljopynsmecxqzgpra.supabase.co';
const STAGING_SUPABASE_PUBLISHABLE_KEY = 'sb_publishable_n0T9ibtda16AK6QDDV1uhA_g6u6abda';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function isPreviewHostname(hostname: string): boolean {
  const value = hostname.toLowerCase();
  return value.endsWith('.vercel.app') && value.includes('-git-') && !value.includes('-git-main-');
}

function resolveBrowserSupabaseConfig() {
  const preview = typeof window !== 'undefined' && isPreviewHostname(window.location.hostname);
  return preview
    ? { url: STAGING_SUPABASE_URL, key: STAGING_SUPABASE_PUBLISHABLE_KEY }
    : { url: PRODUCTION_SUPABASE_URL, key: PRODUCTION_SUPABASE_PUBLISHABLE_KEY };
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseClient() {
  const config = resolveBrowserSupabaseConfig();
  return createClient<Database>(config.url, config.key, {
    global: {
      fetch: createSupabaseFetch(config.key),
    },
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
